/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Views.Admin;

import Controllers.*;
import Views.Customer.CustomerHomeCard;
import Views.Customer.CustomerStockMarketCard;
import Views.LoginPage;

import javax.swing.*;
import java.awt.*;

/**
 *
 * @author zeqi
 */
public class AdminMainPage extends javax.swing.JFrame {
    int customerID;

    private AdminHomeController adminHomeController;
    private AdminMarketController adminMarketController;
    private CustomerTradingHistoryController customerTradingHistoryController;
    private LoginController loginController;
    private SignupController signupController;
    private AllUserTradingHistoryController allUserTradingHistoryController;

    /**
     * Creates new form AdminMainPage
     */
    public AdminMainPage(int customerID, AdminHomeController adminHomeController, LoginController loginController, SignupController signupController, CustomerTradingHistoryController customerTradingHistoryController, AdminMarketController adminMarketController, AllUserTradingHistoryController allUserTradingHistoryController) {
        this.adminHomeController = adminHomeController;
        this.adminMarketController = adminMarketController;
        this.customerTradingHistoryController = customerTradingHistoryController;
        this.loginController = loginController;
        this.signupController = signupController;
        this.allUserTradingHistoryController = allUserTradingHistoryController;
        this.customerID = customerID;
        initComponents();

        cardLayout = new CardLayout();
        PNLMotherCard.setLayout(cardLayout);


        //show panels here
        //TODO: when refresh buttons being clicked, update all the pages, check here for reference about how to render a new page
        //Dashboard - Home directly open this page when initialized
        PNLAdminHomeCard = new AdminHomeCard(adminHomeController,customerTradingHistoryController, allUserTradingHistoryController);
        PNLMotherCard.add(PNLAdminHomeCard,"Home");
        // Change Dashboard styles by default the first page will be Home Page
        LBLHomePage.setBackground(Color.WHITE);
        LBLHomePage.setForeground(themeColor);
        LBLStockMarket.setBackground(themeColor);
        LBLStockMarket.setForeground(Color.WHITE);

        //Dashboard - Stock Market
        PNLAdminStockMarketCard = new AdminStockMarketCard(adminMarketController);
        PNLMotherCard.add(PNLAdminStockMarketCard,"StockMarket");

        BTNRefresh.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PNLMain = new javax.swing.JPanel();
        PNLDashBoard = new javax.swing.JPanel();
        LBLStockMarket = new javax.swing.JLabel();
        LBLHomePage = new javax.swing.JLabel();
        BTNRefresh = new javax.swing.JButton();
        LBLAdminUsername = new javax.swing.JLabel();
        LBLTitle = new javax.swing.JLabel();
        BTNLogout = new javax.swing.JButton();
        PNLMotherCard = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        PNLMain.setBackground(new java.awt.Color(255, 255, 255));
        PNLMain.setPreferredSize(new java.awt.Dimension(1200, 700));
        PNLMain.setLayout(new java.awt.BorderLayout());

        PNLDashBoard.setBackground(new java.awt.Color(0, 102, 255));
        PNLDashBoard.setPreferredSize(new java.awt.Dimension(300, 700));
        PNLDashBoard.setSize(new java.awt.Dimension(300, 700));

        LBLStockMarket.setBackground(new java.awt.Color(0, 102, 255));
        LBLStockMarket.setFont(new java.awt.Font("Arial Unicode MS", 0, 20)); // NOI18N
        LBLStockMarket.setForeground(new java.awt.Color(255, 255, 255));
        LBLStockMarket.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LBLStockMarket.setText("Stock Market");
        LBLStockMarket.setOpaque(true);
        LBLStockMarket.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LBLStockMarketMouseClicked(evt);
            }
        });

        LBLHomePage.setBackground(new java.awt.Color(0, 102, 255));
        LBLHomePage.setFont(new java.awt.Font("Arial Unicode MS", 0, 20)); // NOI18N
        LBLHomePage.setForeground(new java.awt.Color(255, 255, 255));
        LBLHomePage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LBLHomePage.setText("Home Page");
        LBLHomePage.setOpaque(true);
        LBLHomePage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LBLHomePageMouseClicked(evt);
            }
        });

        BTNRefresh.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        BTNRefresh.setForeground(new java.awt.Color(0, 102, 255));
        BTNRefresh.setText("Refresh");
        BTNRefresh.setAlignmentX(0.5F);
        BTNRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNRefreshActionPerformed(evt);
            }
        });

        LBLAdminUsername.setBackground(new java.awt.Color(0, 102, 255));
        LBLAdminUsername.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 20)); // NOI18N
        LBLAdminUsername.setForeground(new java.awt.Color(255, 255, 255));
        LBLAdminUsername.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
//        LBLAdminUsername.setText("Get boss name from DB");
        LBLAdminUsername.setOpaque(true);

        LBLTitle.setBackground(new java.awt.Color(0, 102, 255));
        LBLTitle.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 22)); // NOI18N
        LBLTitle.setForeground(new java.awt.Color(255, 255, 153));
        LBLTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LBLTitle.setText("Admin The Boss");
        LBLTitle.setOpaque(true);

        BTNLogout.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        BTNLogout.setForeground(new java.awt.Color(0, 102, 255));
        BTNLogout.setText("Log Out");
        BTNLogout.setAlignmentX(0.5F);
        BTNLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNLogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PNLDashBoardLayout = new javax.swing.GroupLayout(PNLDashBoard);
        PNLDashBoard.setLayout(PNLDashBoardLayout);
        PNLDashBoardLayout.setHorizontalGroup(
                PNLDashBoardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(LBLTitle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(LBLAdminUsername, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(PNLDashBoardLayout.createSequentialGroup()
                                .addGap(109, 109, 109)
                                .addComponent(BTNRefresh)
                                .addGap(0, 0, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PNLDashBoardLayout.createSequentialGroup()
                                .addContainerGap(43, Short.MAX_VALUE)
                                .addGroup(PNLDashBoardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(LBLHomePage, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(PNLDashBoardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PNLDashBoardLayout.createSequentialGroup()
                                                        .addComponent(LBLStockMarket, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(42, 42, 42))
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PNLDashBoardLayout.createSequentialGroup()
                                                        .addComponent(BTNLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(51, 51, 51)))))
        );
        PNLDashBoardLayout.setVerticalGroup(
                PNLDashBoardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(PNLDashBoardLayout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addComponent(LBLTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(LBLAdminUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(67, 67, 67)
                                .addComponent(LBLHomePage, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(60, 60, 60)
                                .addComponent(LBLStockMarket, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(123, 123, 123)
                                .addComponent(BTNRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 95, Short.MAX_VALUE)
                                .addComponent(BTNLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26))
        );

        PNLMain.add(PNLDashBoard, java.awt.BorderLayout.WEST);

        PNLMotherCard.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout PNLMotherCardLayout = new javax.swing.GroupLayout(PNLMotherCard);
        PNLMotherCard.setLayout(PNLMotherCardLayout);
        PNLMotherCardLayout.setHorizontalGroup(
                PNLMotherCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 900, Short.MAX_VALUE)
        );
        PNLMotherCardLayout.setVerticalGroup(
                PNLMotherCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 700, Short.MAX_VALUE)
        );

        PNLMain.add(PNLMotherCard, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(PNLMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(PNLMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(1200, 728));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void LBLStockMarketMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LBLStockMarketMouseClicked
        // Change Dashboard styles
        LBLStockMarket.setBackground(Color.WHITE);
        LBLStockMarket.setForeground(themeColor);
        LBLHomePage.setBackground(themeColor);
        LBLHomePage.setForeground(Color.WHITE);

        //TODO: show panel here
        PNLMotherCard.remove(PNLAdminStockMarketCard);
        PNLAdminStockMarketCard = new AdminStockMarketCard(adminMarketController);
        PNLMotherCard.add(PNLAdminStockMarketCard,"StockMarket");
        cardLayout.show(PNLMotherCard,"StockMarket");
    }//GEN-LAST:event_LBLStockMarketMouseClicked

    private void LBLHomePageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LBLHomePageMouseClicked
        // Change Dashboard styles
        LBLHomePage.setBackground(Color.WHITE);
        LBLHomePage.setForeground(themeColor);
        LBLStockMarket.setBackground(themeColor);
        LBLStockMarket.setForeground(Color.WHITE);

        //TODO: show panel here
        PNLMotherCard.remove(PNLAdminHomeCard);
        PNLAdminHomeCard = new AdminHomeCard(adminHomeController,customerTradingHistoryController, allUserTradingHistoryController);
        PNLMotherCard.add(PNLAdminHomeCard,"Home");
        cardLayout.show(PNLMotherCard,"Home");
    }//GEN-LAST:event_LBLHomePageMouseClicked

    private void BTNRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNRefreshActionPerformed
        // TODO This button is to refresh the latest database to all the pages
        //  (especially when price changed or edited by admin and many others)
    }//GEN-LAST:event_BTNRefreshActionPerformed

    private void BTNLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNLogoutActionPerformed
        //shows a dialog to double-check if user wants to log out
        int result = JOptionPane.showConfirmDialog(
                this,
                "Are you sure you want to log out?",
                "Logout Confirmation",
                JOptionPane.YES_NO_OPTION);
        if (result == JOptionPane.YES_OPTION) {
            // Handle logout
            System.out.println("User has logged out.");
            dispose();
            new LoginPage(loginController, signupController).setVisible(true);
        } else {
            // Do nothing, user canceled logout
        }
    }//GEN-LAST:event_BTNLogoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminMainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminMainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminMainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminMainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new AdminMainPage(1, admin).setVisible(true);
//            }
//        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNLogout;
    private javax.swing.JButton BTNRefresh;
    private javax.swing.JLabel LBLAdminUsername;
    private javax.swing.JLabel LBLHomePage;
    private javax.swing.JLabel LBLStockMarket;
    private javax.swing.JLabel LBLTitle;
    private javax.swing.JPanel PNLDashBoard;
    private javax.swing.JPanel PNLMain;
    private javax.swing.JPanel PNLMotherCard;
    // End of variables declaration//GEN-END:variables

    private AdminHomeCard PNLAdminHomeCard;
    private AdminStockMarketCard PNLAdminStockMarketCard;
    private CardLayout cardLayout;
    private Color themeColor = new Color(0,102,255);
}
