package Views;


import Controllers.LoginController;
import Controllers.SignupController;
import Views.Customer.CustomerMainPage;

import javax.swing.*;
import java.awt.*;
//import Frontend.SignUpPage;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 * @author zeqi
 */
public class LoginPage extends javax.swing.JFrame {

    private LoginController loginController;
    private SignupController signupController;

    /**
     * Creates new form LoginPage
     */
    public LoginPage(LoginController loginController, SignupController signupController) {
        this.signupController = signupController;
        this.loginController = loginController;
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {


        PNLWelcome = new javax.swing.JPanel();
        LBLAppName = new javax.swing.JLabel();
        LBLWelcomeMsg1 = new javax.swing.JLabel();
        LBLWelcomeMsg2 = new javax.swing.JLabel();
        LBLWelcomeMsg3 = new javax.swing.JLabel();
        LBLWelcomeMsg4 = new javax.swing.JLabel();
        LBLDesignedBy = new javax.swing.JLabel();
        LBLTeamName = new javax.swing.JLabel();
        PNLLogin = new javax.swing.JPanel();
        LBLLogin = new javax.swing.JLabel();
        LBLUsername = new javax.swing.JLabel();
        LBLPassword = new javax.swing.JLabel();
        BTNLogin = new javax.swing.JButton();
        TXTUsername = new javax.swing.JTextField();
        TXTPassword = new javax.swing.JPasswordField();
        LBLAskForSignUp = new javax.swing.JLabel();
        LBLToSignUpPage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1200, 700));
        setResizable(false);

        PNLWelcome.setBackground(new java.awt.Color(0, 102, 255));
        PNLWelcome.setPreferredSize(new java.awt.Dimension(500, 600));

        LBLAppName.setBackground(new java.awt.Color(0, 102, 255));
        LBLAppName.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 24)); // NOI18N
        LBLAppName.setForeground(new java.awt.Color(255, 255, 255));
        LBLAppName.setText("T8 Stock Simulator");

        LBLWelcomeMsg1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 13)); // NOI18N
        LBLWelcomeMsg1.setForeground(new java.awt.Color(255, 255, 255));
        LBLWelcomeMsg1.setText("Experience the power of virtual stock trading");

        LBLWelcomeMsg2.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 13)); // NOI18N
        LBLWelcomeMsg2.setForeground(new java.awt.Color(255, 255, 255));
        LBLWelcomeMsg2.setText("and hone your investment skills.");

        LBLWelcomeMsg3.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        LBLWelcomeMsg3.setForeground(new java.awt.Color(255, 255, 255));
        LBLWelcomeMsg3.setText("with confidence!");

        LBLWelcomeMsg4.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        LBLWelcomeMsg4.setForeground(new java.awt.Color(255, 255, 255));
        LBLWelcomeMsg4.setText("Join now and start building your portfolio ");

        LBLDesignedBy.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        LBLDesignedBy.setForeground(new java.awt.Color(255, 255, 255));
        LBLDesignedBy.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LBLDesignedBy.setText("Designed By");

        LBLTeamName.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 10)); // NOI18N
        LBLTeamName.setForeground(new java.awt.Color(255, 255, 255));
        LBLTeamName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LBLTeamName.setText("Zeqi Wang      Vineet Raju      Zhou Ye");

        javax.swing.GroupLayout PNLWelcomeLayout = new javax.swing.GroupLayout(PNLWelcome);
        PNLWelcome.setLayout(PNLWelcomeLayout);
        PNLWelcomeLayout.setHorizontalGroup(
                PNLWelcomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PNLWelcomeLayout.createSequentialGroup()
                                .addContainerGap(43, Short.MAX_VALUE)
                                .addGroup(PNLWelcomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(LBLAppName, javax.swing.GroupLayout.PREFERRED_SIZE, 428, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(LBLWelcomeMsg3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 436, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(LBLWelcomeMsg4, javax.swing.GroupLayout.PREFERRED_SIZE, 403, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(PNLWelcomeLayout.createSequentialGroup()
                                                .addGap(23, 23, 23)
                                                .addGroup(PNLWelcomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(LBLWelcomeMsg2, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(LBLWelcomeMsg1, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(21, 21, 21))
                        .addGroup(PNLWelcomeLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(PNLWelcomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(LBLTeamName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(LBLDesignedBy, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap())
        );
        PNLWelcomeLayout.setVerticalGroup(
                PNLWelcomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(PNLWelcomeLayout.createSequentialGroup()
                                .addGap(58, 58, 58)
                                .addComponent(LBLAppName, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(LBLWelcomeMsg1)
                                .addGap(0, 0, 0)
                                .addComponent(LBLWelcomeMsg2)
                                .addGap(117, 117, 117)
                                .addComponent(LBLWelcomeMsg4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(LBLWelcomeMsg3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 225, Short.MAX_VALUE)
                                .addComponent(LBLDesignedBy, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(LBLTeamName)
                                .addGap(19, 19, 19))
        );

        getContentPane().add(PNLWelcome, java.awt.BorderLayout.WEST);

        PNLLogin.setBackground(new java.awt.Color(255, 255, 255));
        PNLLogin.setPreferredSize(new java.awt.Dimension(300, 361));

        LBLLogin.setFont(new java.awt.Font("Arial Rounded MT Bold", Font.PLAIN, 24)); // NOI18N
        LBLLogin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LBLLogin.setText("Login");

        LBLUsername.setFont(new java.awt.Font("Arial Rounded MT Bold", Font.BOLD, 14)); // NOI18N
        LBLUsername.setText("Username");

        LBLPassword.setFont(new java.awt.Font("Arial Rounded MT Bold", Font.BOLD, 14)); // NOI18N
        LBLPassword.setText("Password");

        BTNLogin.setBackground(new java.awt.Color(0, 102, 255));
        BTNLogin.setFont(new java.awt.Font("Arial Rounded MT Bold", Font.PLAIN, 18)); // NOI18N
        BTNLogin.setForeground(new java.awt.Color(255, 255, 255));
        BTNLogin.setText("Login");
        BTNLogin.setAlignmentX(0.5F);
        BTNLogin.addActionListener(loginController);
        loginController.setPasswordField(TXTPassword);
        loginController.setUsernameField(TXTUsername);
        loginController.setLoginPage(this);

        TXTUsername.setToolTipText("Enter Your Username");

        TXTPassword.setPreferredSize(new java.awt.Dimension(180, 33));
        TXTPassword.setSize(new java.awt.Dimension(300, 34));
        TXTPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTPasswordActionPerformed(evt);
            }
        });

        LBLAskForSignUp.setText("Don't have an account?");

        LBLToSignUpPage.setBackground(new java.awt.Color(255, 255, 255));
        LBLToSignUpPage.setForeground(new java.awt.Color(0, 102, 255));
        LBLToSignUpPage.setText("Sign Up");
        LBLToSignUpPage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LBLToSignUpPageMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout PNLLoginLayout = new javax.swing.GroupLayout(PNLLogin);
        PNLLogin.setLayout(PNLLoginLayout);
        PNLLoginLayout.setHorizontalGroup(
                PNLLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PNLLoginLayout.createSequentialGroup()
                                .addContainerGap(63, Short.MAX_VALUE)
                                .addComponent(LBLLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(322, 322, 322))
                        .addGroup(PNLLoginLayout.createSequentialGroup()
                                .addGap(93, 93, 93)
                                .addGroup(PNLLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(PNLLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(LBLPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(LBLUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(BTNLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(TXTPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 266, Short.MAX_VALUE)
                                                .addComponent(TXTUsername))
                                        .addGroup(PNLLoginLayout.createSequentialGroup()
                                                .addGap(27, 27, 27)
                                                .addComponent(LBLAskForSignUp)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(LBLToSignUpPage)))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PNLLoginLayout.setVerticalGroup(
                PNLLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PNLLoginLayout.createSequentialGroup()
                                .addGap(59, 59, 59)
                                .addComponent(LBLLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(45, 45, 45)
                                .addComponent(LBLUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TXTUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(LBLPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TXTPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(54, 54, 54)
                                .addComponent(BTNLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 128, Short.MAX_VALUE)
                                .addGroup(PNLLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(LBLAskForSignUp)
                                        .addComponent(LBLToSignUpPage))
                                .addGap(61, 61, 61))
        );

        getContentPane().add(PNLLogin, java.awt.BorderLayout.CENTER);

        setSize(new java.awt.Dimension(1000, 626));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BTNLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNLoginActionPerformed
        // TODO add your handling code here:

//        System.out.println("Login Button Clicked");
//        int customerID = 0;
//        boolean validEnter = true;
//        //Pass data to DB
//
//        //Fetch and match the data for validity
//
//        //if not valid, show a warning dialog, here's an example
//        if (validEnter) {
//            CustomerMainPage customerMainPage = new CustomerMainPage(customerID);
//            customerMainPage.setVisible(true);
//            this.setVisible(false);
//        } else {
//            JOptionPane.showMessageDialog(this, "Please enter your information",
//                    "Warning", JOptionPane.WARNING_MESSAGE);
//        }


        //if validity checked: Start the new Page for customer/admin
    }//GEN-LAST:event_BTNLoginActionPerformed

    private void TXTPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTPasswordActionPerformed

    private void CHBAdminLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CHBAdminLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CHBAdminLoginActionPerformed

    private void LBLToSignUpPageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LBLToSignUpPageMouseClicked
        // TODO add your handling code here:
        //Go to Sign Up Page
        SignUpPage signUpPage = new SignUpPage(signupController);
        signUpPage.setVisible(true);
    }//GEN-LAST:event_LBLToSignUpPageMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new LoginPage().setVisible(true);
//            }
//        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNLogin;
    private javax.swing.JLabel LBLAppName;
    private javax.swing.JLabel LBLAskForSignUp;
    private javax.swing.JLabel LBLDesignedBy;
    private javax.swing.JLabel LBLLogin;
    private javax.swing.JLabel LBLPassword;
    private javax.swing.JLabel LBLTeamName;
    private javax.swing.JLabel LBLToSignUpPage;
    private javax.swing.JLabel LBLUsername;
    private javax.swing.JLabel LBLWelcomeMsg1;
    private javax.swing.JLabel LBLWelcomeMsg2;
    private javax.swing.JLabel LBLWelcomeMsg3;
    private javax.swing.JLabel LBLWelcomeMsg4;
    private javax.swing.JPanel PNLLogin;
    private javax.swing.JPanel PNLWelcome;
    private javax.swing.JPasswordField TXTPassword;
    private javax.swing.JTextField TXTUsername;
    // End of variables declaration//GEN-END:variables

}
