/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Views;

import Controllers.SignupController;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.GroupLayout;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JPasswordField;
import javax.swing.JTextField;
import javax.swing.LayoutStyle;
import javax.swing.SwingConstants;
import javax.swing.WindowConstants;

/**
 * @author zeqi
 */
public class SignUpPage extends javax.swing.JFrame {

    /**
     * Creates new form SignUpPage
     */

    private SignupController signupController;


    public SignUpPage() {
        initComponents();
    }

    public SignUpPage(SignupController signupController) {
        this.signupController = signupController;
        initComponents();
    }

    /*
     * Setter method for singupController
     */
    public void setSignupController(SignupController signupController) {
        this.signupController = signupController;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new JTextField();
        PNLLogin = new JPanel();
        LBLLogin = new JLabel();
        LBLFirstName = new JLabel();
        LBLPassword = new JLabel();
        BTNRegister = new JButton();
        TXTFirstName = new JTextField();
        TXTPassword = new JPasswordField();
        LBLLastName = new JLabel();
        TXTLastName = new JTextField();
        LBLEmail = new JLabel();
        LBLRePassword = new JLabel();
        TXTRePassword = new JPasswordField();
        TXTEmail = new JTextField();
        LBLUNTXT = new JLabel();
        TXTUsername = new JTextField();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        PNLLogin.setBackground(new Color(255, 255, 255));
        PNLLogin.setPreferredSize(new Dimension(500, 600));

        LBLLogin.setFont(new Font("Arial Rounded MT Boli", 0, 24)); // NOI18N
        LBLLogin.setHorizontalAlignment(SwingConstants.CENTER);
        LBLLogin.setText("Register");

        LBLFirstName.setFont(new Font("Arial Rounded MT Boli", 1, 14)); // NOI18N
        LBLFirstName.setText("First Name");

        LBLPassword.setFont(new Font("Arial Rounded MT Boli", 1, 14)); // NOI18N
        LBLPassword.setText("Password");

        BTNRegister.setBackground(new Color(0, 102, 255));
        BTNRegister.setFont(new Font("Arial Rounded MT Boli", 0, 18)); // NOI18N
        BTNRegister.setForeground(new Color(255, 255, 255));
        BTNRegister.setText("Register");
        BTNRegister.setAlignmentX(0.5F);
        BTNRegister.addActionListener(signupController);
        signupController.setSignUpPage(this);
        signupController.setFirstNameField(TXTFirstName);
        signupController.setLastNameField(TXTLastName);
        signupController.setEmailField(TXTEmail);
        signupController.setUsernameField(TXTUsername);
        signupController.setPasswordField(TXTPassword);
        signupController.setConfirmPasswordField(TXTRePassword);

        TXTFirstName.setToolTipText("Enter Your FirstName");
        TXTFirstName.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                TXTFirstNameActionPerformed(evt);
            }
        });

        TXTPassword.setToolTipText("Enter your password");
        TXTPassword.setPreferredSize(new Dimension(180, 33));
        TXTPassword.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                TXTPasswordActionPerformed(evt);
            }
        });

        LBLLastName.setFont(new Font("Arial Rounded MT Boli", 1, 14)); // NOI18N
        LBLLastName.setText("Last Name");

        TXTLastName.setToolTipText("Enter Your Last Name");

        LBLEmail.setFont(new Font("Arial Rounded MT Boli", 1, 14)); // NOI18N
        LBLEmail.setText("E-mail");

        LBLRePassword.setFont(new Font("Arial Rounded MT Boli", 1, 14)); // NOI18N
        LBLRePassword.setText("Re-enter Password");

        TXTRePassword.setToolTipText("Reenter your password, should match the first one you entered");
        TXTRePassword.setPreferredSize(new Dimension(180, 33));
        TXTRePassword.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                TXTRePasswordActionPerformed(evt);
            }
        });

        TXTEmail.setToolTipText("Enter Your Email");

        LBLUNTXT.setFont(new Font("Arial Rounded MT Boli", 1, 14)); // NOI18N
        LBLUNTXT.setText("Username");

        TXTUsername.setToolTipText("Enter Your Last Name");

        GroupLayout PNLLoginLayout = new GroupLayout(PNLLogin);
        PNLLogin.setLayout(PNLLoginLayout);
        PNLLoginLayout.setHorizontalGroup(PNLLoginLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                .addGroup(GroupLayout.Alignment.TRAILING, PNLLoginLayout.createSequentialGroup()
                        .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(LBLLogin, GroupLayout.PREFERRED_SIZE, 115, GroupLayout.PREFERRED_SIZE)
                        .addGap(193, 193, 193))
                .addGroup(PNLLoginLayout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addGroup(PNLLoginLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                .addGroup(PNLLoginLayout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                                        .addComponent(TXTUsername)
                                        .addComponent(LBLUNTXT, GroupLayout.PREFERRED_SIZE, 266, GroupLayout.PREFERRED_SIZE))
                                .addComponent(TXTEmail, GroupLayout.PREFERRED_SIZE, 266, GroupLayout.PREFERRED_SIZE)
                                .addGroup(PNLLoginLayout.createParallelGroup(GroupLayout.Alignment.TRAILING)
                                        .addGroup(PNLLoginLayout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                                                .addComponent(TXTFirstName, GroupLayout.DEFAULT_SIZE, 266, Short.MAX_VALUE)
                                                .addComponent(TXTPassword, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(TXTLastName, GroupLayout.DEFAULT_SIZE, 266, Short.MAX_VALUE)
                                                .addComponent(TXTRePassword, GroupLayout.DEFAULT_SIZE, 266, Short.MAX_VALUE)
                                                .addComponent(LBLRePassword, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(LBLPassword, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(LBLEmail, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(LBLLastName, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(LBLFirstName, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addComponent(BTNRegister, GroupLayout.PREFERRED_SIZE, 266, GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(117, Short.MAX_VALUE))
        );
        PNLLoginLayout.setVerticalGroup(PNLLoginLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                .addGroup(GroupLayout.Alignment.TRAILING, PNLLoginLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(LBLLogin, GroupLayout.PREFERRED_SIZE, 62, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(LBLFirstName, GroupLayout.PREFERRED_SIZE, 24, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TXTFirstName, GroupLayout.PREFERRED_SIZE, 33, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LBLLastName, GroupLayout.PREFERRED_SIZE, 24, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TXTLastName, GroupLayout.PREFERRED_SIZE, 33, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LBLUNTXT, GroupLayout.PREFERRED_SIZE, 24, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TXTUsername, GroupLayout.PREFERRED_SIZE, 33, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(LBLEmail, GroupLayout.PREFERRED_SIZE, 24, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TXTEmail, GroupLayout.PREFERRED_SIZE, 33, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LBLPassword, GroupLayout.PREFERRED_SIZE, 24, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TXTPassword, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LBLRePassword, GroupLayout.PREFERRED_SIZE, 24, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TXTRePassword, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(BTNRegister, GroupLayout.PREFERRED_SIZE, 40, GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52))
        );

        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                .addComponent(PNLLogin, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(PNLLogin, GroupLayout.PREFERRED_SIZE, 598, GroupLayout.PREFERRED_SIZE))
        );

        setSize(new Dimension(500, 628));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents


    private void BTNRegisterActionPerformed(ActionEvent evt) {//GEN-FIRST:event_BTNRegisterActionPerformed
        // TODO add your handling code here:
        System.out.println("Register Button Clicked");

        //Check all the text fields and check box's validity

        //Once validity checked, pass data to DB

        //if not valid, show warning messages, here's an example
        JOptionPane.showMessageDialog(this, "Please enter your infomation", "Warning", JOptionPane.WARNING_MESSAGE);

        // Close the window
        this.setVisible(false);
        this.dispose();

    }//GEN-LAST:event_BTNRegisterActionPerformed

    private void TXTPasswordActionPerformed(ActionEvent evt) {//GEN-FIRST:event_TXTPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTPasswordActionPerformed

    private void CHBAdminRegistorActionPerformed(ActionEvent evt) {//GEN-FIRST:event_CHBAdminRegistorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CHBAdminRegistorActionPerformed

    private void TXTRePasswordActionPerformed(ActionEvent evt) {//GEN-FIRST:event_TXTRePasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTRePasswordActionPerformed

    private void TXTFirstNameActionPerformed(ActionEvent evt) {//GEN-FIRST:event_TXTFirstNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTFirstNameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignUpPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignUpPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignUpPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignUpPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignUpPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JButton BTNRegister;
    private JLabel LBLEmail;
    private JLabel LBLFirstName;
    private JLabel LBLLastName;
    private JLabel LBLLogin;
    private JLabel LBLPassword;
    private JLabel LBLRePassword;
    private JLabel LBLUNTXT;
    private JPanel PNLLogin;
    private JTextField TXTEmail;
    private JTextField TXTFirstName;
    private JTextField TXTLastName;
    private JPasswordField TXTPassword;
    private JPasswordField TXTRePassword;
    private JTextField TXTUsername;
    private JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}

