/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Views.Customer;

import Controllers.CustomerStockMarketActionMenuController;
import Controllers.CustomerStockMarketController;
import Views.StockGraphPanel;

import javax.swing.*;
import java.sql.Timestamp;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

/**
 * @author zeqi
 */
public class StockMarketActionMenu extends javax.swing.JFrame {

    private CustomerStockMarketActionMenuController customerStockMarketActionMenuController;
    private String stockname;
    private String stockSymbol;
    private int customerID;

    /**
     * Creates new form StockMarketActionMenu
     */
    public StockMarketActionMenu(CustomerStockMarketActionMenuController customerStockMarketActionMenuController, String stockName, String stockSymbol, int customerID) {
        this.customerStockMarketActionMenuController = customerStockMarketActionMenuController;
        customerStockMarketActionMenuController.setStockMarketActionMenu(this);
        this.stockname = stockName;
        this.stockSymbol = stockSymbol;
        this.customerID = customerID;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        LBLCPTXT = new javax.swing.JLabel();
        LBLCurrentPrice = new javax.swing.JLabel();
        LBLSTXT = new javax.swing.JLabel();
        LBLNumberOfShares = new javax.swing.JLabel();
        LBLCTXT = new javax.swing.JLabel();
        LBLCost = new javax.swing.JLabel();
        LBLTTXT = new javax.swing.JLabel();
        LBLTradable = new javax.swing.JLabel();
        LBLATXT = new javax.swing.JLabel();
        BTNBuy = new javax.swing.JButton();
        LBLExtendiableNote = new javax.swing.JLabel();
        BTNGetHistory = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText(stockname);

        LBLCPTXT.setText("Current Price: $");

        LBLCurrentPrice.setText(customerStockMarketActionMenuController.getStockPrice(stockSymbol));

        LBLSTXT.setText("# of Shares:");

        LBLNumberOfShares.setText(customerStockMarketActionMenuController.getNumberOfShares(stockSymbol, customerID));

        LBLCTXT.setText("Cost: $");

        LBLCost.setText(customerStockMarketActionMenuController.getInvestedByStock(stockSymbol, customerID));

        LBLTTXT.setText("Tradeable:");

        LBLTradable.setText(customerStockMarketActionMenuController.getStockTradable(stockSymbol));

        LBLATXT.setText("Actions: ");

        BTNBuy.setForeground(new java.awt.Color(255, 0, 0));
        BTNBuy.setText("Buy");
        BTNBuy.addActionListener(customerStockMarketActionMenuController);

        LBLExtendiableNote.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LBLExtendiableNote.setText("Extendable functions for future");

        BTNGetHistory.setText("Get Price History Graph");
        BTNGetHistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNGetHistoryActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap(20, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(BTNGetHistory)
                                                .addGroup(layout.createSequentialGroup()
                                                        .addComponent(LBLCPTXT)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(LBLCurrentPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(layout.createSequentialGroup()
                                                        .addComponent(LBLCTXT)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(LBLCost, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(LBLATXT)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(BTNBuy)
                                                .addGap(108, 108, 108)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(LBLTTXT)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(LBLTradable, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(LBLSTXT)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(LBLNumberOfShares, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(29, 29, 29))
                        .addComponent(LBLExtendiableNote, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(LBLCPTXT, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(LBLCurrentPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(LBLSTXT, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(LBLNumberOfShares, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(LBLCTXT, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(LBLCost, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(LBLTTXT, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(LBLTradable, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(33, 33, 33)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(LBLATXT)
                                        .addComponent(BTNBuy))
                                .addGap(46, 46, 46)
                                .addComponent(BTNGetHistory)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 271, Short.MAX_VALUE)
                                .addComponent(LBLExtendiableNote)
                                .addGap(141, 141, 141))
        );

        setSize(new java.awt.Dimension(500, 628));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BTNGetHistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNGetHistoryActionPerformed
        // TODO add your handling code here:
        System.out.println("Admin get price history clicked");
        List<List<String>> stockUpdateData = customerStockMarketActionMenuController.getStockUpdateData(stockSymbol);
        if(stockUpdateData.size() <2 ){
            JOptionPane.showMessageDialog(null, "Graph will only display after at least two price changes", "Warning", JOptionPane.WARNING_MESSAGE);
        }else {
            SwingUtilities.invokeLater(() -> {
                JFrame frame = new JFrame("Stock Price Graph");
                List<Object[]> dataPoints = new ArrayList<>();
                for (List<String> data : stockUpdateData){
                    double price = Double.parseDouble(data.get(0));
                    Timestamp time = Timestamp.valueOf(data.get(1));
                    dataPoints.add(new Object[]{price,time});
                }
                frame.add(new StockGraphPanel(dataPoints));
                frame.setSize(800, 600);
                frame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
                frame.setVisible(true);
            });
        }
    }//GEN-LAST:event_BTNGetHistoryActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StockMarketActionMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StockMarketActionMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StockMarketActionMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StockMarketActionMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new StockMarketActionMenu().setVisible(true);
//            }
//        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNBuy;
    private javax.swing.JButton BTNGetHistory;
    private javax.swing.JLabel LBLATXT;
    private javax.swing.JLabel LBLCPTXT;
    private javax.swing.JLabel LBLCTXT;
    private javax.swing.JLabel LBLCost;
    private javax.swing.JLabel LBLCurrentPrice;
    private javax.swing.JLabel LBLExtendiableNote;
    private javax.swing.JLabel LBLNumberOfShares;
    private javax.swing.JLabel LBLSTXT;
    private javax.swing.JLabel LBLTTXT;
    private javax.swing.JLabel LBLTradable;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

    /**
     * Getter for the buy button
     */
    public JButton getBTNBuy() {
        return BTNBuy;
    }

    /**
     * Getter for stock name
     */
    public String getStockName() {
        return stockname;
    }

    /**
     * Getter for stock symbol
     */
    public String getStockSymbol() {
        return stockSymbol;
    }

    /**
     * Getter for customer ID
     */
    public int getCustomerID() {
        return customerID;
    }
}
