/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Views.Customer;

import Controllers.*;
import Views.LoginPage;

import javax.swing.*;
import java.awt.*;
import java.util.ArrayList;
import java.util.HashMap;

/**
 *
 * @author zeqi
 */
public class CustomerMainPage extends javax.swing.JFrame {

    private static int customerID;
    private LoginController loginController;
    private SignupController signupController;
    private CustomerHomeController customerHomeController;
    private CustomerStockMarketController customerStockMarketController;
    private CustomerStockAccountController customerStockAccountController;
    private CustomerTradingHistoryController customerTradingHistoryController;
    private CustomerStockMarketActionMenuController customerStockMarketActionMenuController;


    /**
     * Creates new form CustomerMainPage
     */
    public CustomerMainPage(int CustomerID, LoginController loginController, SignupController signupController, CustomerHomeController customerHomeController, CustomerStockMarketController customerStockMarketController, CustomerStockAccountController customerStockAccountController, CustomerTradingHistoryController customerTradingHistoryController, CustomerStockMarketActionMenuController customerStockMarketActionMenuController){
        this.loginController = loginController;
        this.signupController = signupController;
        this.customerHomeController = customerHomeController;
        this.customerStockMarketController = customerStockMarketController;
        this.customerStockAccountController = customerStockAccountController;
        this.customerTradingHistoryController = customerTradingHistoryController;
        this.customerStockMarketActionMenuController = customerStockMarketActionMenuController;
        this.customerID = CustomerID;
        initComponents();
        setResizable(false);

        //TODO: update content based on database customer id
//        LBLUsername.setText();


        //Extra components modification here, don't modify the netbeans codes
        BTNLogout.setBackground(Color.white);

        //Defining content mother panel as card layout
        cardLayout = new CardLayout();
        PNLMotherCard.setLayout(cardLayout);


        //show panels here
        //TODO: when refresh buttons being clicked, update all the pages, check here for reference about how to render a new page
        //Dashboard - Home directly open this page when initialized
        PNLCustomerHomeCard = new CustomerHomeCard(customerID, customerHomeController, customerTradingHistoryController);
        PNLMotherCard.add(PNLCustomerHomeCard,"Home");


        // Change Dashboard styles by default the first page will be Home Page
        LBLHomePage.setBackground(Color.WHITE);
        LBLHomePage.setForeground(themeColor);
        LBLStockAccounts.setBackground(themeColor);
        LBLStockAccounts.setForeground(Color.WHITE);
        LBLStockMarket.setBackground(themeColor);
        LBLStockMarket.setForeground(Color.WHITE);

        //Dashboard - Stock Account
        PNLCustomerStockAccount = new CustomerStockAccountCard(customerID, customerStockAccountController, customerStockMarketActionMenuController);
        PNLMotherCard.add(PNLCustomerStockAccount,"StockAccount");
        PNLCustomerStockAccount.updateContent();

        //Dashboard - Stock Market
        PNLCustomerStockMarket = new CustomerStockMarketCard(customerID, customerStockMarketController, customerStockMarketActionMenuController);
        PNLMotherCard.add(PNLCustomerStockMarket,"StockMarket");
        BTNRefresh.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PNLMain = new javax.swing.JPanel();
        PNLDashBoard = new javax.swing.JPanel();
        LBLStockMarket = new javax.swing.JLabel();
        LBLHomePage = new javax.swing.JLabel();
        LBLStockAccounts = new javax.swing.JLabel();
        BTNRefresh = new javax.swing.JButton();
        LBLUsername = new javax.swing.JLabel();
        LBLCustomerTXT = new javax.swing.JLabel();
        BTNLogout = new javax.swing.JButton();
        PNLMotherCard = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PNLMain.setPreferredSize(new java.awt.Dimension(1200, 700));
        PNLMain.setSize(new java.awt.Dimension(1200, 700));
        PNLMain.setLayout(new java.awt.BorderLayout());

        PNLDashBoard.setBackground(new java.awt.Color(0, 102, 255));
        PNLDashBoard.setPreferredSize(new java.awt.Dimension(300, 700));
        PNLDashBoard.setSize(new java.awt.Dimension(300, 700));

        LBLStockMarket.setBackground(new java.awt.Color(0, 102, 255));
        LBLStockMarket.setFont(new java.awt.Font("Arial Unicode MS", 0, 20)); // NOI18N
        LBLStockMarket.setForeground(new java.awt.Color(255, 255, 255));
        LBLStockMarket.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LBLStockMarket.setText("Stock Market");
        LBLStockMarket.setOpaque(true);
        LBLStockMarket.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LBLStockMarketMouseClicked(evt);
            }
        });

        LBLHomePage.setBackground(new java.awt.Color(0, 102, 255));
        LBLHomePage.setFont(new java.awt.Font("Arial Unicode MS", 0, 20)); // NOI18N
        LBLHomePage.setForeground(new java.awt.Color(255, 255, 255));
        LBLHomePage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LBLHomePage.setText("Home Page");
        LBLHomePage.setOpaque(true);
        LBLHomePage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LBLHomePageMouseClicked(evt);
            }
        });

        LBLStockAccounts.setBackground(new java.awt.Color(0, 102, 255));
        LBLStockAccounts.setFont(new java.awt.Font("Arial Unicode MS", 0, 20)); // NOI18N
        LBLStockAccounts.setForeground(new java.awt.Color(255, 255, 255));
        LBLStockAccounts.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LBLStockAccounts.setText("Stock Accounts");
        LBLStockAccounts.setOpaque(true);
        LBLStockAccounts.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LBLStockAccountsMouseClicked(evt);
            }
        });

        BTNRefresh.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        BTNRefresh.setForeground(new java.awt.Color(0, 102, 255));
        BTNRefresh.setText("Refresh");
        BTNRefresh.setAlignmentX(0.5F);
        BTNRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNRefreshActionPerformed(evt);
            }
        });

        LBLUsername.setBackground(new java.awt.Color(0, 102, 255));
        LBLUsername.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 20)); // NOI18N
        LBLUsername.setForeground(new java.awt.Color(255, 255, 255));
        LBLUsername.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
//        LBLUsername.setText("Zeqi Wang");
        LBLUsername.setOpaque(true);

        LBLCustomerTXT.setBackground(new java.awt.Color(0, 102, 255));
        LBLCustomerTXT.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 22)); // NOI18N
        LBLCustomerTXT.setForeground(new java.awt.Color(255, 255, 153));
        LBLCustomerTXT.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LBLCustomerTXT.setText("Welcome Customer");
        LBLCustomerTXT.setOpaque(true);

        BTNLogout.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        BTNLogout.setForeground(new java.awt.Color(0, 102, 255));
        BTNLogout.setText("Log Out");
        BTNLogout.setAlignmentX(0.5F);
        BTNLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNLogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PNLDashBoardLayout = new javax.swing.GroupLayout(PNLDashBoard);
        PNLDashBoard.setLayout(PNLDashBoardLayout);
        PNLDashBoardLayout.setHorizontalGroup(
                PNLDashBoardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(LBLCustomerTXT, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(LBLUsername, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PNLDashBoardLayout.createSequentialGroup()
                                .addContainerGap(43, Short.MAX_VALUE)
                                .addGroup(PNLDashBoardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PNLDashBoardLayout.createSequentialGroup()
                                                .addGroup(PNLDashBoardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(LBLHomePage, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(LBLStockAccounts, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(LBLStockMarket, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(42, 42, 42))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PNLDashBoardLayout.createSequentialGroup()
                                                .addComponent(BTNLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(51, 51, 51))))
                        .addGroup(PNLDashBoardLayout.createSequentialGroup()
                                .addGap(109, 109, 109)
                                .addComponent(BTNRefresh)
                                .addGap(0, 0, Short.MAX_VALUE))
        );
        PNLDashBoardLayout.setVerticalGroup(
                PNLDashBoardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(PNLDashBoardLayout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addComponent(LBLCustomerTXT, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(LBLUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33)
                                .addComponent(LBLHomePage, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(56, 56, 56)
                                .addComponent(LBLStockAccounts, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(56, 56, 56)
                                .addComponent(LBLStockMarket, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(47, 47, 47)
                                .addComponent(BTNRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 95, Short.MAX_VALUE)
                                .addComponent(BTNLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26))
        );

        PNLMain.add(PNLDashBoard, java.awt.BorderLayout.WEST);

        PNLMotherCard.setBackground(new java.awt.Color(255, 255, 255));
        PNLMotherCard.setLayout(new java.awt.CardLayout());
        PNLMain.add(PNLMotherCard, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(PNLMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(PNLMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(1200, 728));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BTNRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNRefreshActionPerformed
        // TODO This button is to refresh the latest database to all the pages
        //  (especially when price changed or edited by admin and many others)
    }//GEN-LAST:event_BTNRefreshActionPerformed

    private void BTNLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNLogoutActionPerformed
        //shows a dialog to double-check if user wants to log out
        int result = JOptionPane.showConfirmDialog(
                this,
                "Are you sure you want to log out?",
                "Logout Confirmation",
                JOptionPane.YES_NO_OPTION);
        if (result == JOptionPane.YES_OPTION) {
            // Handle logout
            System.out.println("User has logged out.");
            dispose();
            new LoginPage(loginController, signupController).setVisible(true);
        } else {
            // Do nothing, user canceled logout
        }

    }//GEN-LAST:event_BTNLogoutActionPerformed

    private void LBLHomePageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LBLHomePageMouseClicked
        // Change Dashboard styles
        LBLHomePage.setBackground(Color.WHITE);
        LBLHomePage.setForeground(themeColor);
        LBLStockAccounts.setBackground(themeColor);
        LBLStockAccounts.setForeground(Color.WHITE);
        LBLStockMarket.setBackground(themeColor);
        LBLStockMarket.setForeground(Color.WHITE);

        //TODO: show panel here
        // want to have the home page refresh every time it is clicked
        System.out.println("Home page clicked");
//        PNLCustomerHomeCard.revalidate();
//        PNLCustomerHomeCard.repaint();
        PNLMotherCard.remove(PNLCustomerHomeCard);
        PNLCustomerHomeCard = new CustomerHomeCard(customerID, customerHomeController, customerTradingHistoryController);
        PNLMotherCard.add(PNLCustomerHomeCard,"Home");
        PNLCustomerHomeCard.showNotificationDialog();
        cardLayout.show(PNLMotherCard,"Home");


    }//GEN-LAST:event_LBLHomePageMouseClicked

    private void LBLStockAccountsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LBLStockAccountsMouseClicked
        // Change Dashboard styles
        LBLStockAccounts.setBackground(Color.WHITE);
        LBLStockAccounts.setForeground(themeColor);
        LBLHomePage.setBackground(themeColor);
        LBLHomePage.setForeground(Color.WHITE);
        LBLStockMarket.setBackground(themeColor);
        LBLStockMarket.setForeground(Color.WHITE);

        //TODO: show panel here
        System.out.println("Stock Accounts clicked");
        PNLMotherCard.remove(PNLCustomerStockAccount);
        PNLCustomerStockAccount = new CustomerStockAccountCard(customerID, customerStockAccountController, customerStockMarketActionMenuController);
        PNLMotherCard.add(PNLCustomerStockAccount,"StockAccount");
        PNLCustomerStockAccount.updateContent();
        cardLayout.show(PNLMotherCard,"StockAccount");
    }//GEN-LAST:event_LBLStockAccountsMouseClicked

    private void LBLStockMarketMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LBLStockMarketMouseClicked
        // Change Dashboard styles
        LBLStockMarket.setBackground(Color.WHITE);
        LBLStockMarket.setForeground(themeColor);
        LBLStockAccounts.setBackground(themeColor);
        LBLStockAccounts.setForeground(Color.WHITE);
        LBLHomePage.setBackground(themeColor);
        LBLHomePage.setForeground(Color.WHITE);

        //TODO: show panel here
        System.out.println("Stock Market clicked");
//        PNLCustomerStockMarket.revalidate();
//        PNLCustomerStockMarket.repaint();
        PNLMotherCard.remove(PNLCustomerStockMarket);
        PNLCustomerStockMarket = new CustomerStockMarketCard(customerID, customerStockMarketController, customerStockMarketActionMenuController);
        PNLMotherCard.add(PNLCustomerStockMarket,"StockMarket");
        cardLayout.show(PNLMotherCard,"StockMarket");
    }//GEN-LAST:event_LBLStockMarketMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CustomerMainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CustomerMainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CustomerMainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustomerMainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new CustomerMainPage(customerID, null, null, null).setVisible(true);
//            }
//        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNRefresh;
    private javax.swing.JButton BTNLogout;
    private javax.swing.JLabel LBLAppName;
    private javax.swing.JLabel LBLCustomerTXT;
    private javax.swing.JLabel LBLHomePage;
    private javax.swing.JLabel LBLStockAccounts;
    private javax.swing.JLabel LBLStockMarket;
    private javax.swing.JLabel LBLUsername;
    private javax.swing.JPanel PNLMotherCard;
    private javax.swing.JPanel PNLDashBoard;
    private javax.swing.JPanel PNLMain;
    // End of variables declaration//GEN-END:variables

    private CustomerHomeCard PNLCustomerHomeCard;
    private CustomerStockAccountCard PNLCustomerStockAccount;
    private CustomerStockMarketCard PNLCustomerStockMarket;
    private CardLayout cardLayout;
    private Color themeColor = new Color(0,102,255);

    public static int getCustomerID() {
        return customerID;
    }

    public static void setCustomerID(int customerID) {
        CustomerMainPage.customerID = customerID;
    }
}
